extends: default
rules:
  line-length:
    max: 160
    level: warning
  document-start: disable
  comments:
    min-spaces-from-content: 1
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  trailing-spaces: disable
  comments-indentation: disable
ignore: |
  .github/
  node_modules/
  venv/
